---
- name: Открываем порты http,https (80,443)
  firewalld: service={{ item }}
             permanent=true
             state=enabled
  with_items:
    - http
    - https
  notify:
    - firewalld reload
