---

- name: Копируем конфигурационный файл сайта для nginx
  template:
    src: nginx_site.conf
    dest: /etc/nginx/conf.d/{{ SITE_NAME }}.conf
    owner: root
    group: root
    mode: 0664
  notify:
    - nginx reload
